// data.js — tutti i casi del gioco, estratti dal dossier "Vita nell'universo".
// Contenuto esterno al codice: aggiungere un caso = aggiungere una riga qui.
//
// Livelli di prova (regola d'oro del dossier):
//   A = PROVATO        (osservazione ripetuta, strumenti calibrati, consenso)
//   B = INDIZIO        (dato reale e interessante, ma non conclusivo)
//   C = IPOTESI        (proposta testabile che guida esperimenti, non una scoperta)
//   D = NON VERIFICATO (mancano dati controllabili o replicabili)

export const LEVELS = {
  A: { key: "A", label: "PROVATO",        short: "Provato",        color: "#3ddc84", desc: "Osservato e ripetuto, con consenso scientifico." },
  B: { key: "B", label: "INDIZIO",        short: "Indizio",        color: "#4aa8ff", desc: "Dato reale ma non conclusivo: restano spiegazioni alternative." },
  C: { key: "C", label: "IPOTESI",        short: "Ipotesi",        color: "#b98cff", desc: "Idea testabile che guida la ricerca, non ancora una scoperta." },
  D: { key: "D", label: "NON VERIFICATO", short: "Non verif.",     color: "#ff5d6c", desc: "Mancano dati controllabili: affermazione non dimostrata." },
};

export const CATEGORIES = {
  origine:    { name: "Origine della vita", glyph: "origine" },
  marte:      { name: "Marte",              glyph: "marte" },
  lune:       { name: "Lune oceaniche",     glyph: "lune" },
  esopianeti: { name: "Esopianeti",         glyph: "esopianeti" },
  seti:       { name: "SETI e segnali",     glyph: "seti" },
  uap:        { name: "UAP / UFO",          glyph: "uap" },
  archivi:    { name: "Archivi antichi",    glyph: "archivi" },
  cosmo:      { name: "Cosmo",              glyph: "cosmo" },
};

// answer = livello corretto secondo il dossier.
export const CASES = [
  // ————— ORIGINE DELLA VITA —————
  { id: 1, cat: "origine", title: "Esperimento di Miller-Urey (1953)",
    claim: "Facendo passare scariche elettriche in una miscela di acqua, metano, ammoniaca e idrogeno si formano amminoacidi, i mattoni delle proteine.",
    answer: "A",
    why: "Chimica reale e ripetibile: alcune molecole biologiche nascono senza organismi, in condizioni energetiche plausibili. Ma NON crea una cellula, un genoma o la vita: dimostra la plausibilità di alcuni passaggi, non l'origine della vita." },
  { id: 2, cat: "origine", title: "Il mondo a RNA",
    claim: "Prima del DNA e delle proteine, molecole simili all'RNA portavano l'informazione e catalizzavano le reazioni della prima vita.",
    answer: "C",
    why: "Filone di ricerca serio e influente, ma la sintesi credibile dei nucleotidi, la loro polimerizzazione e il passaggio a DNA/proteine restano problemi aperti. È un'ipotesi di lavoro che guida gli esperimenti." },
  { id: 3, cat: "origine", title: "Esperimento di Redi (1668)",
    claim: "In condizioni controllate gli insetti non compaiono spontaneamente dalla carne: servono uova deposte da altri insetti.",
    answer: "A",
    why: "Esperimento controllato e ripetibile, pietra miliare del metodo scientifico. Ha smontato la 'generazione spontanea' come spiegazione della vita." },
  { id: 4, cat: "origine", title: "Pasteur, i palloni a collo di cigno (1861)",
    claim: "L'aria non genera automaticamente vita: i microrganismi in un brodo sterile arrivano da contaminanti esterni.",
    answer: "A",
    why: "Risultato osservato e ripetuto. Attenzione: la biogenesi non esclude un'abiogenesi antica in condizioni diversissime; cambia il problema, non lo chiude." },
  { id: 5, cat: "origine", title: "Panspermia",
    claim: "La vita, o i suoi precursori, è arrivata sulla Terra viaggiando nello spazio su rocce o granelli di polvere.",
    answer: "C",
    why: "Ipotesi in parte testabile ma non confermata. Anche se fosse vera, sposterebbe solo il luogo di origine: non spiega come la vita sia nata la prima volta." },
  { id: 6, cat: "origine", title: "Stromatoliti di Dresser (3,48 miliardi di anni)",
    claim: "Le strutture sedimentarie della Dresser Formation (Australia) sono resti di antiche comunità microbiche.",
    answer: "B",
    why: "Più linee di evidenza sono compatibili con attività microbica: è un indizio forte. Ma le rocce antichissime possono produrre strutture simili senza vita, quindi va sempre valutato contro imitazioni abiologiche." },
  { id: 7, cat: "origine", title: "Microstrutture dell'Apex chert",
    claim: "Le microstrutture dell'Apex chert (3,5 miliardi di anni) sono i più antichi microfossili conosciuti della Terra.",
    answer: "D",
    why: "Pubblicate come microfossili, ma analisi successive con tecniche migliori hanno contestato l'interpretazione biologica. È il caso-scuola su come cambiano le conclusioni: la lettura come vita non regge." },
  { id: 8, cat: "origine", title: "Carbonio negli zirconi (4,1 miliardi di anni)",
    claim: "Il carbonio intrappolato in cristalli di zircone di 4,1 miliardi di anni è la firma della vita più antica mai trovata.",
    answer: "D",
    why: "Alcuni studi hanno proposto segnali potenzialmente biogenici, ma il significato è molto controverso e non conclusivo: mancano prove controllabili che escludano origini non biologiche." },
  { id: 44, cat: "origine", title: "Origine nelle sorgenti idrotermali",
    claim: "La vita è iniziata nelle sorgenti idrotermali oceaniche, dove minerali e gradienti chimici hanno alimentato le prime reazioni.",
    answer: "C",
    why: "È uno dei principali scenari di ricerca ('metabolism-first'), con esperimenti in corso. Manca però il passaggio dimostrato da cicli chimici a ereditarietà e membrane: resta un'ipotesi di lavoro." },

  // ————— MARTE —————
  { id: 9, cat: "marte", title: "Viking, esperimento Labeled Release (1976)",
    claim: "Il Labeled Release del Viking rilevò gas dopo l'aggiunta di nutrienti al suolo marziano: è la firma di un metabolismo microbico.",
    answer: "B",
    why: "Il segnale è reale e si ripeté ai due siti, ma anche reazioni chimiche del suolo possono produrne di simili, e il GC/MS non trovò organici attesi. Risultato corretto: ambiguità persistente, non vita provata né esclusa." },
  { id: 10, cat: "marte", title: "Meteorite ALH84001 (1996)",
    claim: "Il meteorite marziano ALH84001 contiene microstrutture, carbonati e magnetite che sono fossili di antica vita su Marte.",
    answer: "B",
    why: "Meteorite reale, studiato per decenni. Ma ogni singola linea di prova ha ricevuto spiegazioni abiologiche o problemi di contaminazione: nessun consenso di vita marziana. Caso non conclusivo." },
  { id: 11, cat: "marte", title: "Perseverance, campione 'Sapphire Canyon' (2024-25)",
    claim: "Il campione Sapphire Canyon, raccolto da Perseverance a Cheyava Falls, contiene biosignature potenziali di vita marziana.",
    answer: "B",
    why: "La NASA parla esplicitamente di biosignature POTENZIALI: indica che serve altro studio, non un annuncio di vita. Restano possibili spiegazioni geochimiche. Indizio da confermare." },
  { id: 12, cat: "marte", title: "I 'canali' di Marte",
    claim: "I canali osservati da Schiaparelli e interpretati da Lowell sono opere di ingegneria di una civiltà marziana.",
    answer: "D",
    why: "Immagini migliori e analisi successive hanno mostrato il ruolo di illusioni ottiche e aspettative. L'idea è stata abbandonata: nessun dato la sostiene." },
  { id: 13, cat: "marte", title: "Molecole organiche su Marte",
    claim: "Curiosity ha rilevato molecole organiche e variazioni di metano nelle rocce di Marte.",
    answer: "A",
    why: "La RILEVAZIONE è solida e ripetuta. Ma attenzione al tranello: 'organico' significa 'a base di carbonio', non 'biologico'. Le molecole possono avere origini non viventi. Il dato è provato, la vita no." },
  { id: 14, cat: "marte", title: "Marte antico abitabile",
    claim: "Miliardi di anni fa Marte ebbe acqua liquida in superficie e ambienti potenzialmente abitabili.",
    answer: "A",
    why: "Prove geologiche solide e indipendenti: delta fluviali, minerali formatisi in acqua, letti di antichi laghi. 'Abitabile' però non vuol dire 'abitato'." },

  // ————— LUNE OCEANICHE —————
  { id: 15, cat: "lune", title: "L'oceano di Europa",
    claim: "Sotto la crosta ghiacciata di Europa, luna di Giove, si nasconde un oceano globale di acqua liquida: un mondo potenzialmente abitabile.",
    answer: "B",
    why: "Le evidenze di un oceano interno e di scambi con la superficie sono forti; Europa Clipper (lanciata nel 2024) ne studierà l'abitabilità. Ma nessun organismo è stato rilevato: è un ambiente promettente, non vita." },
  { id: 16, cat: "lune", title: "I pennacchi di Encelado",
    claim: "I geyser di Encelado (luna di Saturno) sprigionano acqua, sali, molecole organiche e idrogeno: possibile energia chimica per microbi.",
    answer: "B",
    why: "Cassini ha misurato davvero questi composti: indizi ambientali forti di abitabilità. Ma nessuna cellula è stata osservata; la fonte d'energia potenziale non è un organismo." },
  { id: 17, cat: "lune", title: "I laghi di Titano",
    claim: "Titano ha laghi di idrocarburi e una chimica organica ricca: un laboratorio prebiotico naturale.",
    answer: "C",
    why: "Ambiente affascinante con chimica molto diversa dalla Terra e possibile interesse prebiotico. Ma è un'idea da esplorare: nessuna vita è confermata e la sua chimica potrebbe non portare a biologia." },
  { id: 18, cat: "lune", title: "La fosfina di Venere",
    claim: "La fosfina rilevata nelle nubi di Venere è prodotta da microrganismi che vivono nell'atmosfera.",
    answer: "D",
    why: "L'intensità del segnale, la sua identificazione e la chimica sono state contestate da rianalisi indipendenti. Nessuna vita è dedotta: affermazione non verificata." },

  // ————— ESOPIANETI —————
  { id: 19, cat: "esopianeti", title: "Esistono gli esopianeti",
    claim: "Attorno ad altre stelle esistono pianeti: gli esopianeti confermati sono oltre 6.000.",
    answer: "A",
    why: "Categoria fisica pienamente stabilita, con migliaia di conferme indipendenti dal 1995 (51 Pegasi b). Che ESISTANO è provato; che siano abitati è tutt'altra domanda." },
  { id: 20, cat: "esopianeti", title: "K2-18 b e il DMS",
    claim: "Su K2-18 b il telescopio JWST ha trovato metano, CO2 e forse DMS: è un mondo oceanico che ospita vita.",
    answer: "B",
    why: "Gli spettri mostrano molecole di carbonio reali, ma il DMS è un candidato discusso, esistono vie di formazione non biologiche e nessun oceano è stato osservato direttamente. Indizio interessante, niente biosignature confermata." },
  { id: 21, cat: "esopianeti", title: "Pianeti nella zona abitabile",
    claim: "I molti esopianeti che orbitano nella 'zona abitabile' delle loro stelle ospitano vita.",
    answer: "C",
    why: "Che esistano pianeti nella zona abitabile è confermato; che siano davvero abitabili dipende da atmosfera, superficie e stella, caso per caso. La presenza di vita resta un'ipotesi da testare." },
  { id: 22, cat: "esopianeti", title: "Ossigeno = vita?",
    claim: "Se in un'atmosfera esoplanetaria troviamo ossigeno, allora su quel pianeta c'è vita.",
    answer: "C",
    why: "Sulla Terra l'ossigeno è legato alla fotosintesi, ma può formarsi anche per processi fotochimici o perdita d'acqua. Un solo gas non basta: serve un contesto coerente. È un criterio da verificare, non una prova." },

  // ————— SETI E SEGNALI —————
  { id: 23, cat: "seti", title: "Il Wow! signal (1977)",
    claim: "Il Wow! signal, un forte impulso radio captato una volta nel 1977, è un messaggio di una civiltà aliena.",
    answer: "D",
    why: "Evento reale e intenso, ma registrato UNA sola volta, mai ripetuto, con origine tuttora irrisolta. 'Non spiegato' non significa 'alieno': manca qualunque verifica indipendente." },
  { id: 24, cat: "seti", title: "L'equazione di Drake",
    claim: "L'equazione di Drake calcola quante civiltà tecnologiche esistono nella nostra galassia.",
    answer: "C",
    why: "È uno strumento per organizzare le incognite e ragionare, non una misura: molti dei suoi termini sono sconosciuti. Serve a porre bene la domanda, non a dare un numero dimostrato." },
  { id: 25, cat: "seti", title: "Decenni di ricerca SETI",
    claim: "Dopo oltre 60 anni di ricerche (da Project Ozma a Breakthrough Listen), nessuna tecnosignatura extraterrestre è stata confermata.",
    answer: "A",
    why: "Fatto documentato sull'esito delle ricerche: molti candidati controllati, nessuno ha superato la verifica di ripetizione e origine non terrestre. È un risultato reale, non una prova che gli alieni non esistano." },
  { id: 26, cat: "seti", title: "Il paradosso di Fermi",
    claim: "Il paradosso di Fermi ('se ci sono, dove sono tutti?') dimostra che le civiltà aliene non esistono.",
    answer: "C",
    why: "Non è una dimostrazione: è un modo per elencare possibilità (vita rara, distanze enormi, durata breve, strumenti limitati...). Resta un ragionamento aperto, non una prova." },

  // ————— UAP / UFO —————
  { id: 27, cat: "uap", title: "Roswell (1947)",
    claim: "Nel 1947 a Roswell l'esercito statunitense recuperò un veicolo alieno precipitato.",
    answer: "D",
    why: "Gli archivi e le indagini ufficiali disponibili non hanno fornito alcuna prova verificabile di tecnologia extraterrestre. Il caso resta culturalmente famoso, ma non dimostrato." },
  { id: 28, cat: "uap", title: "Rapporto storico AARO (2024)",
    claim: "Dopo aver esaminato archivi classificati e non, l'ufficio AARO del Pentagono non ha trovato prove verificabili di tecnologia extraterrestre o recuperi non umani.",
    answer: "A",
    why: "È la conclusione documentata di un'indagine ufficiale su decenni di materiale (1945-2023). Un esito verificabile — che, ovviamente, potrebbe cambiare solo con prove materiali future." },
  { id: 29, cat: "uap", title: "Gli archivi del Project Blue Book",
    claim: "I documenti del Project Blue Book sull'attività UFO (1947-1969) sono declassificati e consultabili al National Archives.",
    answer: "A",
    why: "Fatto verificabile: gli archivi esistono e si possono consultare. Attenzione: che un ente abbia indagato un fenomeno prova che l'indagine c'è stata, non che il contenuto confermi origini aliene." },
  { id: 30, cat: "uap", title: "'Non identificato' = alieno?",
    claim: "Un fenomeno aereo classificato come 'non identificato' (UAP) è, per definizione, una tecnologia aliena.",
    answer: "D",
    why: "'Non identificato' descrive lo stato del DATO (scarso, non calibrato, ambiguo), non la natura dell'oggetto. Può essere un pallone, un drone, un artefatto dei sensori. Non è una prova di origine non umana." },
  { id: 31, cat: "uap", title: "Oltre 1.600 casi in revisione",
    claim: "Il Dipartimento della Difesa ha comunicato oltre 1.600 casi UAP in revisione, dei quali una parte resta non risolta.",
    answer: "A",
    why: "Il numero è reale e comunicato ufficialmente (2024). Ma 'non risolto' indica qualità insufficiente dei dati, non un'origine extraterrestre: il fatto amministrativo è provato, la spiegazione aliena no." },

  // ————— ARCHIVI ANTICHI —————
  { id: 32, cat: "archivi", title: "Il meccanismo di Anticitera",
    claim: "Il meccanismo di Anticitera è un calcolatore astronomico costruito dai greci con decine di ingranaggi di bronzo.",
    answer: "A",
    why: "Tomografie, iscrizioni e ricostruzioni lo confermano come tecnologia ellenistica eccezionale ma pienamente umana. Complessità sorprendente non significa origine impossibile o aliena." },
  { id: 33, cat: "archivi", title: "La mappa di Piri Reis (1513)",
    claim: "La mappa di Piri Reis mostra l'Antartide libera dai ghiacci, impossibile da disegnare senza una veduta aerea.",
    answer: "D",
    why: "La lettura cartografica non sostiene questa tesi: proiezioni, fonti parziali e deformazioni spiegano le corrispondenze apparenti. La mappa raffigura soprattutto coste atlantiche note e deformate." },
  { id: 34, cat: "archivi", title: "Le linee di Nazca",
    claim: "I giganteschi geoglifi di Nazca sono piste di atterraggio costruite per le astronavi.",
    answer: "D",
    why: "L'archeologia li interpreta come opere culturali, rituali e territoriali della civiltà andina. Forma e scala imponenti non sono prove di infrastrutture aerospaziali." },
  { id: 35, cat: "archivi", title: "Le tavolette astronomiche babilonesi",
    claim: "Le tavolette tardo-babilonesi registrano osservazioni sistematiche di stelle, mesi e segni zodiacali.",
    answer: "A",
    why: "Documenti reali e datati (ne conserva il British Museum): testimoniano l'inizio di un'astronomia osservativa sistematica. Sono l'alba della scienza del cielo, non un messaggio alieno." },
  { id: 36, cat: "archivi", title: "I geroglifici come 'codice tecnologico'",
    claim: "I geroglifici egizi nascondono un codice tecnologico lasciato da visitatori extraterrestri.",
    answer: "D",
    why: "I geroglifici sono una lingua complessa e decifrata, con grammatica e usi documentati. Non c'è alcun codice nascosto: è un'affermazione priva di prove controllabili." },

  // ————— COSMO —————
  { id: 37, cat: "cosmo", title: "L'età dell'universo",
    claim: "L'universo ha circa 13,8 miliardi di anni.",
    answer: "A",
    why: "Sostenuto da più linee indipendenti: espansione cosmica, fondo cosmico a microonde e abbondanze degli elementi leggeri. Uno dei risultati più solidi della cosmologia." },
  { id: 38, cat: "cosmo", title: "Gli elementi nascono nelle stelle",
    claim: "Il carbonio, l'ossigeno e l'azoto della nostra biochimica sono stati fabbricati dentro le stelle e dispersi da venti stellari e supernove.",
    answer: "A",
    why: "La nucleosintesi stellare è stabilita: senza generazioni di stelle precedenti non esisterebbero né i pianeti rocciosi né i mattoni della vita. È il ponte tra cosmo e biologia." },
  { id: 39, cat: "cosmo", title: "L'evoluzione della vita terrestre",
    claim: "La vita sulla Terra si è evoluta e diversificata nel corso di miliardi di anni.",
    answer: "A",
    why: "Sostenuta dal record fossile, dalla biologia molecolare e da innumerevoli linee indipendenti. È un caposaldo stabilito della scienza." },
  { id: 40, cat: "cosmo", title: "I mattoni chimici nello spazio",
    claim: "Comete e meteoriti contengono acqua e molecole organiche, i mattoni della chimica prebiotica.",
    answer: "A",
    why: "Provato per la CHIMICA: questi corpi contengono davvero acqua e composti organici. Ma non sono di per sé organismi: 'mattoni della vita' non è 'vita'." },
  { id: 41, cat: "cosmo", title: "La Grande Ossidazione",
    claim: "Circa 2,4 miliardi di anni fa la fotosintesi riempì di ossigeno l'atmosfera terrestre, trasformando il pianeta.",
    answer: "A",
    why: "Evento stabilito dalla geochimica: fu insieme un'opportunità e una catastrofe, letale per molti organismi anaerobi. Un esempio di come la vita cambia il proprio pianeta." },
  { id: 42, cat: "cosmo", title: "L'impatto di Chicxulub",
    claim: "Un impatto di asteroide circa 66 milioni di anni fa contribuì all'estinzione dei dinosauri non aviari.",
    answer: "A",
    why: "Sostenuto da più prove convergenti (cratere, strato geologico, anomalie chimiche). Dimostra anche che una biosfera può essere sconvolta senza scomparire del tutto." },
  { id: 43, cat: "cosmo", title: "Il Golden Record del Voyager",
    claim: "Il Voyager Golden Record (1977) è un disco con suoni e immagini della Terra lanciato nello spazio.",
    answer: "A",
    why: "Artefatto reale e documentato. Nota bene: è un messaggio culturale spedito da noi verso l'esterno, non un 'contatto' ricevuto da una civiltà aliena." },
];
